### ISSUE TITLE
Notion link is broken

### ISSUE THREAD

**Issue by 71** [the-pudding/rain#2]
The story redirects to [Notion](https://github.com/the-pudding/rain/blob/1e70759f7317152ff13d38180ba761f34c84a4fe/docs/index.html#L343), but visiting this page leads to the following error:

> You do not have access to The Pudding. Please contact an admin to add you as a member.

**Comment by ProQuestionAsker** [comment]
Oops! Thanks for pointing this out. Should be all fixed now :)
